// @vitest-environment node
import { randomUUID } from "node:crypto";
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { eq } from "drizzle-orm";
import {
  fulfillPaidOrder,
  generatePrintFilesForOrder,
  releaseApprovedOrder,
  resendJobSheet,
  retryFulfillment,
} from "./fulfillment";
import { getDb } from "@/lib/db/client";
import {
  artworks,
  fulfillmentEvents,
  orderEmails,
  orderItems,
  orders,
  type OrderStatus,
} from "@/lib/db/schema";
import { getProduct, printPixels } from "@/lib/products";
import { getStorage } from "@/lib/storage";

/**
 * The other half of the money path. The webhook decides an order was paid; this
 * decides what the customer actually receives. Every test here is a way to ship
 * the wrong garment, or to lose an order we have already been paid for.
 *
 * TWO THINGS ARE PINNED THROUGHOUT. Fulfilment NEVER calls the image provider:
 * the print file is a resize of the bytes the customer approved, and a second
 * trip to a non-deterministic model would print a portrait nobody agreed to.
 * And a line that already has a print file is never rebuilt, however many
 * retries, duplicate ITNs and impatient admins arrive.
 *
 * Nothing here touches the network: the provider, the resize and the email
 * helpers are all stubbed, and the assertions are mostly about how many times
 * each was called and with what.
 */

const {
  generatePortraitMock,
  derivePrintBytesMock,
  sendJobSheetMock,
  sendOrderConfirmationMock,
} = vi.hoisted(() => ({
  generatePortraitMock: vi.fn(),
  derivePrintBytesMock: vi.fn(),
  sendJobSheetMock: vi.fn(),
  sendOrderConfirmationMock: vi.fn(),
}));

// The provider is stubbed so that CALLING it is observable. Fulfilment must
// never reach this; every test below asserts it did not.
vi.mock("@/lib/images", async (importOriginal) => ({
  ...(await importOriginal<typeof import("@/lib/images")>()),
  getImageProvider: async () => ({
    moderate: async () => ({ ok: true }),
    generatePortrait: generatePortraitMock,
  }),
}));

vi.mock("@/lib/images/derive", async (importOriginal) => ({
  ...(await importOriginal<typeof import("@/lib/images/derive")>()),
  derivePrintBytes: derivePrintBytesMock,
}));

vi.mock("@/lib/email", async (importOriginal) => ({
  ...(await importOriginal<typeof import("@/lib/email")>()),
  sendJobSheet: sendJobSheetMock,
  sendOrderConfirmation: sendOrderConfirmationMock,
}));

/** A believable print file. PNG magic, so the key gets a .png on it. */
const PNG_BYTES = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/**
 * A REAL 8x8 PNG, generated by sharp itself so it is genuinely decodable.
 *
 * The drawing half composites what the provider returns THROUGH sharp, so the
 * eight magic bytes above are not enough there: the header alone satisfies
 * metadata() and then fails on the pixels, which is how a plausible-looking
 * hand-written base64 quietly turns a happy-path test into a failure-path one.
 */
const REAL_PNG = new Uint8Array(
  Buffer.from(
    "iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEklEQVR4nGOoiLL5jw8zjAwFAIMVg0H5dXQZAAAAAElFTkSuQmCC",
    "base64",
  ),
);

/**
 * The canonical bytes for one artwork, made recognisable by its id so a test can
 * assert WHICH portrait was resized, not merely that something was. A Buffer
 * rather than a bare Uint8Array because that is what comes back out of storage,
 * and these are compared against what fulfilment read.
 */
function canonicalBytesFor(artworkId: string): Buffer {
  return Buffer.from([...PNG_BYTES, ...new TextEncoder().encode(artworkId)]);
}

beforeEach(() => {
  vi.stubEnv("MOCK_SERVICES", "true");
  generatePortraitMock.mockResolvedValue({
    portraitBytes: PNG_BYTES,
    promptVersion: "test",
  });
  derivePrintBytesMock.mockResolvedValue(PNG_BYTES);
  sendJobSheetMock.mockResolvedValue({ ok: true, id: "job-sheet-1" });
  sendOrderConfirmationMock.mockResolvedValue({ ok: true, id: "confirmation-1" });
});

afterEach(() => {
  vi.unstubAllEnvs();
  vi.restoreAllMocks();
  generatePortraitMock.mockReset();
  derivePrintBytesMock.mockReset();
  sendJobSheetMock.mockReset();
  sendOrderConfirmationMock.mockReset();
});

/**
 * An artwork the way the PRINTING half finds one: drawn after payment, both
 * plates stored, and approved by the customer. Approval is part of the fixture
 * because it is a precondition of printing now, not an afterthought: nothing
 * reaches a press without it (docs/spec-pipeline.md section 5).
 *
 * The canonical bytes are really in storage, because reading them back is the
 * first thing the print step does.
 */
async function readyArtwork(productSlug = "hoodie"): Promise<string> {
  const db = await getDb();
  const id = randomUUID();
  const canonicalKey = `portraits/${id}/1.png`;
  await getStorage().put(canonicalKey, canonicalBytesFor(id), "image/png");
  await db.insert(artworks).values({
    id,
    uploadKey: `uploads/${id}.jpg`,
    style: "watercolor",
    canonicalKey,
    promptVersion: "test",
    previewKey: `previews/${id}/1.png`,
    frontKey: `plates/${id}/front-1.png`,
    backKey: `plates/${id}/back-1.png`,
    approvedAt: new Date(),
    status: "ready",
    productSlug,
  });
  return id;
}

/**
 * An artwork the way CHECKOUT leaves one now: uploaded and styled, with no
 * portrait and no approval. This is what the drawing half actually receives,
 * because generation moved after payment.
 */
async function undrawnArtwork(productSlug = "hoodie"): Promise<string> {
  const db = await getDb();
  const id = randomUUID();
  // The upload has to be real bytes: the drawing step reads it.
  await getStorage().put(`uploads/${id}.jpg`, PNG_BYTES, "image/png");
  await db.insert(artworks).values({
    id,
    uploadKey: `uploads/${id}.jpg`,
    style: "watercolor",
    status: "uploaded",
    productSlug,
    creatureName: "Fenn",
    species: "dog",
    breedId: "one-of-one-dog-large",
  });
  return id;
}

/** A paid order whose artwork has not been drawn or approved yet. */
async function unapprovedOrder(
  slugs: string[],
): Promise<{ orderId: string; artworkIds: string[] }> {
  const db = await getDb();
  const orderId = randomUUID();
  await db.insert(orders).values({
    id: orderId,
    status: "paid",
    payfastPaymentId: `pf-${orderId.slice(0, 8)}`,
    email: "thandi@example.co.za",
    firstName: "Thandi",
    lastName: "Mokoena",
    phone: "082 123 4567",
    addressLine1: "14 Loop Street",
    suburb: "Gardens",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
    subtotalZar: 999,
    shippingZar: 99,
    totalZar: 998,
  });

  const artworkIds: string[] = [];
  for (const slug of slugs) {
    const artworkId = await undrawnArtwork(slug);
    artworkIds.push(artworkId);
    await db.insert(orderItems).values({
      orderId,
      productSlug: slug,
      color: "Blue",
      size: "M",
      qty: 1,
      unitPriceZar: 999,
      artworkId,
    });
  }
  return { orderId, artworkIds };
}

/** An order the way the ITN webhook leaves one, with a line per artwork. */
async function orderWith(
  slugs: string[],
  status: OrderStatus = "paid",
  payfastPaymentId: string | null = "1000001",
): Promise<{ orderId: string; artworkIds: string[] }> {
  const db = await getDb();
  const orderId = randomUUID();

  await db.insert(orders).values({
    id: orderId,
    status,
    payfastPaymentId,
    email: "thandi@example.co.za",
    firstName: "Thandi",
    lastName: "Mokoena",
    phone: "082 123 4567",
    addressLine1: "14 Loop Street",
    suburb: "Gardens",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
    subtotalZar: 999,
    shippingZar: 99,
    totalZar: 998,
  });

  const artworkIds: string[] = [];
  for (const slug of slugs) {
    const artworkId = await readyArtwork(slug);
    artworkIds.push(artworkId);
    await db.insert(orderItems).values({
      orderId,
      productSlug: slug,
      color: "Blue",
      size: "M",
      qty: 1,
      unitPriceZar: 999,
      artworkId,
    });
  }

  return { orderId, artworkIds };
}

/**
 * A paid order where ONE artwork (one saved creature) is printed onto several
 * different products, the way a re-order lands (retention B4). This is the case
 * the whole B3 refactor exists for: the same portrait needs a differently sized
 * print file per garment.
 */
async function orderWithSharedArtwork(
  slugs: string[],
): Promise<{ orderId: string; artworkId: string }> {
  const db = await getDb();
  const orderId = randomUUID();
  const artworkId = await readyArtwork(slugs[0]);

  await db.insert(orders).values({
    id: orderId,
    status: "paid",
    payfastPaymentId: "1000002",
    email: "thandi@example.co.za",
    firstName: "Thandi",
    lastName: "Mokoena",
    phone: "082 123 4567",
    addressLine1: "14 Loop Street",
    suburb: "Gardens",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "8001",
    subtotalZar: 999,
    shippingZar: 99,
    totalZar: 998,
  });

  for (const slug of slugs) {
    await db.insert(orderItems).values({
      orderId,
      productSlug: slug,
      color: "Blue",
      size: "M",
      qty: 1,
      unitPriceZar: 999,
      artworkId,
    });
  }

  return { orderId, artworkId };
}

async function readOrder(id: string) {
  const db = await getDb();
  const [row] = await db.select().from(orders).where(eq(orders.id, id));
  return row;
}

async function readArtwork(id: string) {
  const db = await getDb();
  const [row] = await db.select().from(artworks).where(eq(artworks.id, id));
  return row;
}

/** The order's lines, in insertion order, so a test can read their printKeys. */
async function readItems(orderId: string) {
  const db = await getDb();
  return db.select().from(orderItems).where(eq(orderItems.orderId, orderId));
}

async function eventsFor(orderId: string) {
  const db = await getDb();
  return db
    .select()
    .from(fulfillmentEvents)
    .where(eq(fulfillmentEvents.orderId, orderId));
}

describe("fulfillPaidOrder: an order that goes through", () => {
  it("makes a print file per line at 300 DPI and sends it to the printer", async () => {
    const { orderId, artworkIds } = await orderWith(["hoodie", "tote"]);

    const result = await releaseApprovedOrder(orderId);
    expect(result.status).toBe("sent_to_printer");

    // The dimensions are the whole point of the exercise: a print file at the
    // wrong size is a garment printed at the wrong size. It used to be the
    // provider that was asked for them; the resize is asked now, because the
    // picture already exists and only its size is still in question.
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(2);
    for (const [index, slug] of ["hoodie", "tote"].entries()) {
      const { widthPx, heightPx } = printPixels(getProduct(slug)!, "back");
      expect(derivePrintBytesMock).toHaveBeenCalledWith(
        // ...and resized from THAT line's approved portrait, which is what the
        // old assertion on uploadKey and style was really reaching for.
        canonicalBytesFor(artworkIds[index]),
        widthPx,
        heightPx,
      );
    }

    // The print file lives on the order_item now, keyed by the order_item id.
    const items = await readItems(orderId);
    for (const item of items) {
      expect(item.printKey).toMatch(new RegExp(`^prints/${item.id}/\\d+\\.png$`));
    }

    expect(sendJobSheetMock).toHaveBeenCalledTimes(1);
    // NOTE: no confirmation here. The receipt is sent when the money lands
    // (phase A), not when the garment goes to the press.
    expect(sendOrderConfirmationMock).not.toHaveBeenCalled();
    expect((await readOrder(orderId)).status).toBe("sent_to_printer");
  });

  it("never calls the image provider, however ordinary the order", async () => {
    // The most expensive defect this codebase has had. Fulfilment used to ask
    // the model for a fresh print-resolution portrait, and image models are not
    // deterministic, so the customer approved one animal and received another
    // on a personalised, non-returnable garment.
    const { orderId } = await orderWith(["hoodie", "tote"]);

    await releaseApprovedOrder(orderId);

    expect(generatePortraitMock).not.toHaveBeenCalled();
  });

  it("prints the bytes that were approved, not a fresh picture", async () => {
    const { orderId, artworkIds } = await orderWith(["hoodie"]);

    await releaseApprovedOrder(orderId);

    // The exact bytes stored against the artwork, handed to the resize.
    const [bytes] = derivePrintBytesMock.mock.calls[0];
    expect(bytes).toEqual(canonicalBytesFor(artworkIds[0]));
  });

  it("keys each sent mail to the order by its message id (D4)", async () => {
    const jobId = `job-${randomUUID()}`;
    const confId = `conf-${randomUUID()}`;
    sendJobSheetMock.mockResolvedValue({ ok: true, id: jobId });
    sendOrderConfirmationMock.mockResolvedValue({ ok: true, id: confId });
    vi.stubEnv("PRINT_SHOP_EMAIL", "print@example.co.za");

    const { orderId } = await orderWith(["hoodie"]);
    // Both halves, because the two mails now happen in different ones.
    await fulfillPaidOrder(orderId);
    await releaseApprovedOrder(orderId);

    // The delivery ledger is what the Resend webhook joins on later: without
    // these rows a bounce could never find its order.
    const db = await getDb();
    const sends = await db
      .select()
      .from(orderEmails)
      .where(eq(orderEmails.orderId, orderId));
    const byKind = new Map(sends.map((send) => [send.kind, send]));

    expect(byKind.get("job-sheet")).toMatchObject({
      messageId: jobId,
      recipient: "print@example.co.za",
    });
    expect(byKind.get("confirmation")).toMatchObject({
      messageId: confId,
      recipient: "thandi@example.co.za",
    });
  });

  it("hands the job sheet the order items with their print keys on them", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    await releaseApprovedOrder(orderId);

    // The sheet mints its own links from the order_item rows, so a line without
    // a key is a job sheet with a dead link on it. The rows it is handed are the
    // ones read back AFTER generation, so they carry the freshly written key.
    const [, items] = sendJobSheetMock.mock.calls[0];
    expect(items).toHaveLength(1);
    expect(items[0].printKey).toBeTruthy();
  });

  it("hoodie print pixels are the 300 DPI conversion, not a guess", async () => {
    // 280mm / 25.4 * 300 = 3307, 350mm / 25.4 * 300 = 4134. Pinned here because
    // this is the number the print shop cuts against.
    expect(printPixels(getProduct("hoodie")!, "back")).toEqual({
      widthPx: 3307,
      heightPx: 4134,
    });
  });
});

describe("fulfillPaidOrder: not rebuilding a file the shop already has", () => {
  it("does not rebuild or re-send when it runs again", async () => {
    const { orderId } = await orderWith(["hoodie"]);

    const first = await releaseApprovedOrder(orderId);
    const second = await releaseApprovedOrder(orderId);

    expect(first.status).toBe("sent_to_printer");
    // The order is at the printer, so there is nothing to do and no second job
    // sheet to put in their inbox.
    expect(second.status).toBe("already-fulfilled");

    expect(derivePrintBytesMock).toHaveBeenCalledTimes(1);
    expect(generatePortraitMock).not.toHaveBeenCalled();
    // One job sheet, not two. The receipt is phase A's and is not sent here.
    expect(sendJobSheetMock).toHaveBeenCalledTimes(1);
    expect(sendOrderConfirmationMock).not.toHaveBeenCalled();
  });

  it("skips an order item that already has a print file", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    const db = await getDb();
    await db
      .update(orderItems)
      .set({ printKey: "prints/already/there.png" })
      .where(eq(orderItems.orderId, orderId));

    const result = await generatePrintFilesForOrder(orderId);

    expect(result.ok).toBe(true);
    expect(result.lines[0]).toMatchObject({
      ok: true,
      generated: false,
      printKey: "prints/already/there.png",
    });
    // Never remade, because the file already exists and the job sheet already
    // links it.
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect(generatePortraitMock).not.toHaveBeenCalled();
  });
});

describe("fulfillPaidOrder: an artwork with no approved portrait", () => {
  it("flags the order rather than drawing one at fulfilment time", async () => {
    // Belt and braces behind the checkout guard. If a line ever reaches
    // fulfilment with no canonical image, the only safe move is to stop: the
    // customer approved nothing, and a garment is not returnable.
    const { orderId, artworkIds } = await orderWith(["hoodie"]);
    const db = await getDb();
    await db
      .update(artworks)
      .set({ canonicalKey: null })
      .where(eq(artworks.id, artworkIds[0]));
    vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    expect(result.status).toBe("flagged");
    expect(generatePortraitMock).not.toHaveBeenCalled();
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect(sendJobSheetMock).not.toHaveBeenCalled();

    const failure = (await eventsFor(orderId)).find(
      (event) => event.step === "generate-print-file" && event.outcome === "failed",
    );
    expect(failure?.detail).toContain("no approved portrait");
  });

  it("flags when the approved portrait has gone missing from storage", async () => {
    const { orderId, artworkIds } = await orderWith(["hoodie"]);
    const db = await getDb();
    await db
      .update(artworks)
      .set({ canonicalKey: "portraits/gone/missing.png" })
      .where(eq(artworks.id, artworkIds[0]));
    vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    expect(result.status).toBe("flagged");
    expect(generatePortraitMock).not.toHaveBeenCalled();
    const failure = (await eventsFor(orderId)).find(
      (event) => event.step === "generate-print-file" && event.outcome === "failed",
    );
    expect(failure?.detail).toContain("missing from storage");
  });
});

describe("fulfillPaidOrder: one creature across different products (B3)", () => {
  it("makes a distinct, correctly sized print file for each product", async () => {
    // The reason this refactor exists: the SAME artwork on two products must
    // print at two DIFFERENT sizes. hoodie is 280x350mm, tote is 260x300mm, so
    // their 300 DPI pixel dimensions differ, and keying the file on the artwork
    // (the old bug) would have shipped one of them at the wrong size.
    const { orderId, artworkId } = await orderWithSharedArtwork([
      "hoodie",
      "tote",
    ]);

    const result = await releaseApprovedOrder(orderId);
    expect(result.status).toBe("sent_to_printer");

    // One resize per garment, both off the one shared canonical portrait.
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(2);
    // And still no model. Two garments must not mean two different animals.
    expect(generatePortraitMock).not.toHaveBeenCalled();

    const hoodiePx = printPixels(getProduct("hoodie")!, "back");
    const totePx = printPixels(getProduct("tote")!, "back");
    // The two products really are different sizes, or this test proves nothing.
    expect(hoodiePx).not.toEqual(totePx);

    // Each product was made at ITS OWN dimensions, from the one shared set of
    // approved bytes. That the bytes are identical is the point: the same
    // creature on two garments is the same picture at two sizes.
    expect(derivePrintBytesMock).toHaveBeenCalledWith(
      canonicalBytesFor(artworkId),
      hoodiePx.widthPx,
      hoodiePx.heightPx,
    );
    expect(derivePrintBytesMock).toHaveBeenCalledWith(
      canonicalBytesFor(artworkId),
      totePx.widthPx,
      totePx.heightPx,
    );

    // Two order_items, one artwork, two DISTINCT print files.
    const items = await readItems(orderId);
    expect(items).toHaveLength(2);
    const keys = items.map((item) => item.printKey);
    expect(keys.every(Boolean)).toBe(true);
    expect(new Set(keys).size).toBe(2);
    // The legacy artwork.printKey is never touched: it is not the source of
    // truth for a printed file any more, and a re-order must not read it.
    expect((await readArtwork(artworkId)).printKey).toBeNull();
  });

  it("is idempotent per order item: a second run rebuilds nothing", async () => {
    const { orderId } = await orderWithSharedArtwork(["hoodie", "tote"]);

    await releaseApprovedOrder(orderId);
    const keysAfterFirst = (await readItems(orderId)).map((i) => i.printKey);
    // Two files on the first pass, one per garment.
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(2);

    // A second fulfilment is a no-op (order already at the printer): no third or
    // fourth file, and the keys on the rows do not change.
    const second = await releaseApprovedOrder(orderId);
    expect(second.status).toBe("already-fulfilled");
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(2);

    // And even driving the generation step directly changes nothing: every
    // order_item already has a key, so the file the print shop is holding a link
    // to is left exactly as it is.
    await generatePrintFilesForOrder(orderId);
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(2);
    expect(generatePortraitMock).not.toHaveBeenCalled();

    const keysNow = (await readItems(orderId)).map((i) => i.printKey);
    expect(keysNow).toEqual(keysAfterFirst);
    // One job sheet, not two, however many times fulfilment ran.
    expect(sendJobSheetMock).toHaveBeenCalledTimes(1);
  });
});

describe("fulfillPaidOrder: a print file that cannot be made", () => {
  it("flags the order, sends no job sheet, and says why", async () => {
    const { orderId, artworkIds } = await orderWith(["hoodie"]);
    derivePrintBytesMock.mockRejectedValue(new Error("provider is on fire"));
    vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    expect(result.status).toBe("flagged");
    expect((await readOrder(orderId)).status).toBe("flagged");
    // The order is flagged BECAUSE the shop must not be told about a job whose
    // file does not exist.
    expect(sendJobSheetMock).not.toHaveBeenCalled();
    expect((await readItems(orderId))[0].printKey).toBeNull();
    // The shared artwork is a reusable input and must NOT be marked broken by
    // one garment's print failure: other orders may point at this portrait.
    expect((await readArtwork(artworkIds[0])).status).toBe("ready");

    // The breadcrumb: which artwork, which step, what the error said.
    const events = await eventsFor(orderId);
    const failure = events.find(
      (event) => event.step === "generate-print-file" && event.outcome === "failed",
    );
    expect(failure?.artworkId).toBe(artworkIds[0]);
    expect(failure?.detail).toContain("provider is on fire");
    expect(
      events.some((event) => event.step === "fulfil" && event.outcome === "failed"),
    ).toBe(true);
  });

  it("does not un-pay the order it could not print", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    derivePrintBytesMock.mockRejectedValue(new Error("nope"));
    vi.spyOn(console, "error").mockImplementation(() => {});

    await releaseApprovedOrder(orderId);

    // Flagged is a queue, not a refund. The money is still ours to answer for.
    expect((await readOrder(orderId)).payfastPaymentId).toBe("1000001");
  });

  it("flags the whole order when only one line of several fails", async () => {
    const { orderId, artworkIds } = await orderWith(["hoodie", "tote"]);
    derivePrintBytesMock
      .mockResolvedValueOnce(PNG_BYTES)
      .mockRejectedValueOnce(new Error("second one failed"));
    vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    expect(result.status).toBe("flagged");
    // A half-printed order is not a shipped order. The good line keeps its file
    // so the retry leaves it exactly as it is.
    const items = await readItems(orderId);
    const first = items.find((item) => item.artworkId === artworkIds[0]);
    const second = items.find((item) => item.artworkId === artworkIds[1]);
    expect(first!.printKey).toBeTruthy();
    expect(second!.printKey).toBeNull();
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });
});

describe("fulfillPaidOrder: emails that do not send", () => {
  it("keeps the print file and the order when the job sheet bounces", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    sendJobSheetMock.mockResolvedValue({
      ok: false,
      error: new Error("mailbox is down"),
    });
    const logged = vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    // The policy, asserted. A dead mailbox does not lose a print file we have
    // already paid for, and does not drag a paid order backwards.
    expect(result.status).toBe("sent_to_printer");
    expect((await readOrder(orderId)).status).toBe("sent_to_printer");
    expect((await readOrder(orderId)).payfastPaymentId).toBe("1000001");
    expect((await readItems(orderId))[0].printKey).toBeTruthy();

    // But loud: nobody in Cape Town knows this job exists.
    expect(logged).toHaveBeenCalledWith(
      expect.stringContaining("print shop has NOT been told"),
    );
    const events = await eventsFor(orderId);
    expect(
      events.find((event) => event.step === "job-sheet")?.outcome,
    ).toBe("failed");
  });

  it("treats a bounced customer confirmation as a nuisance, not an incident", async () => {
    // The receipt goes out with the payment, so this is phase A's problem now.
    const { orderId } = await orderWith(["hoodie"]);
    sendOrderConfirmationMock.mockResolvedValue({
      ok: false,
      error: new Error("their inbox is full"),
    });

    const result = await fulfillPaidOrder(orderId);

    expect(result.status).toBe("awaiting-approval");
    // A dead mailbox does not cost anybody their order.
    expect((await readOrder(orderId)).status).toBe("paid");
    // Recorded so support can re-send it, and nothing more.
    const events = await eventsFor(orderId);
    expect(
      events.find((event) => event.step === "order-confirmation")?.outcome,
    ).toBe("failed");
  });

  it("keeps the transition when the job sheet failed, and says so loudly", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    sendJobSheetMock.mockResolvedValue({ ok: false, error: new Error("down") });
    const error = vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    // The print files exist and are durable, so losing them to a mailbox
    // outage would be the expensive mistake. The shop can still be told by
    // hand, and the noise is how anyone finds out they have not been.
    expect(result.status).toBe("sent_to_printer");
    expect((await readOrder(orderId)).status).toBe("sent_to_printer");
    expect(error).toHaveBeenCalled();
    const events = await eventsFor(orderId);
    expect(events.find((event) => event.step === "job-sheet")?.outcome).toBe(
      "failed",
    );
  });
});

describe("fulfillPaidOrder: orders it will not touch", () => {
  it("refuses a pending order and never calls the provider", async () => {
    const { orderId } = await orderWith(["hoodie"], "pending", null);

    const result = await releaseApprovedOrder(orderId);

    expect(result).toMatchObject({ status: "refused", reason: "not-paid:pending" });
    // An unpaid order must not reach the print shop, and must not reach the
    // model either: nothing downstream of the state guard runs at all.
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect(generatePortraitMock).not.toHaveBeenCalled();
    expect(sendJobSheetMock).not.toHaveBeenCalled();
    expect((await readOrder(orderId)).status).toBe("pending");
  });

  it("refuses a flagged order rather than printing it", async () => {
    const { orderId } = await orderWith(["hoodie"], "flagged");
    const result = await releaseApprovedOrder(orderId);

    // Flagged means a human has not looked yet. Retry is the way in, not this.
    expect(result).toMatchObject({ status: "refused", reason: "not-paid:flagged" });
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect(generatePortraitMock).not.toHaveBeenCalled();
  });

  it.each<OrderStatus>(["sent_to_printer", "printed", "shipped"])(
    "no-ops on an order already at %s",
    async (status) => {
      const { orderId } = await orderWith(["hoodie"], status);
      const result = await releaseApprovedOrder(orderId);

      expect(result.status).toBe("already-fulfilled");
      expect(sendJobSheetMock).not.toHaveBeenCalled();
      expect((await readOrder(orderId)).status).toBe(status);
    },
  );

  it("refuses an order it has never heard of", async () => {
    const result = await releaseApprovedOrder(
      "00000000-0000-0000-0000-000000000000",
    );
    expect(result).toMatchObject({ status: "refused", reason: "order-not-found" });
  });

  it("flags an order with no lines rather than mailing an empty job sheet", async () => {
    const { orderId } = await orderWith([]);
    vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await releaseApprovedOrder(orderId);

    expect(result.status).toBe("flagged");
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });
});

describe("retryFulfillment", () => {
  it("remakes only the missing line and completes", async () => {
    const { orderId } = await orderWith(["hoodie", "tote"]);
    derivePrintBytesMock
      .mockResolvedValueOnce(PNG_BYTES)
      .mockRejectedValueOnce(new Error("the second one failed"));
    vi.spyOn(console, "error").mockImplementation(() => {});

    expect((await releaseApprovedOrder(orderId)).status).toBe("flagged");
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(2);

    derivePrintBytesMock.mockResolvedValue(PNG_BYTES);
    const retried = await retryFulfillment(orderId);

    expect(retried.status).toBe("sent_to_printer");
    // Three calls, not four: the line that worked the first time keeps the file
    // it already has, and the model is still never asked for anything.
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(3);
    expect(generatePortraitMock).not.toHaveBeenCalled();

    for (const item of await readItems(orderId)) {
      expect(item.printKey).toBeTruthy();
    }
    expect((await readOrder(orderId)).status).toBe("sent_to_printer");
    expect(sendJobSheetMock).toHaveBeenCalledTimes(1);
  });

  it("picks up a paid order whose fulfilment never fired", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    const result = await retryFulfillment(orderId);

    expect(result.status).toBe("sent_to_printer");
    expect(derivePrintBytesMock).toHaveBeenCalledTimes(1);
  });

  it("will not print an order that was flagged without ever being paid", async () => {
    // The one that would cost a garment. The ITN webhook flags an order whose
    // amount did not reconcile, and that order was never paid: it has no
    // payfast_payment_id. Retrying it must not invent one.
    const { orderId } = await orderWith(["hoodie"], "flagged", null);

    const result = await retryFulfillment(orderId);

    expect(result).toMatchObject({
      status: "refused",
      reason: "flagged-without-payment",
    });
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect(generatePortraitMock).not.toHaveBeenCalled();
    expect((await readOrder(orderId)).status).toBe("flagged");
  });

  it("no-ops on an order already at the printer", async () => {
    const { orderId } = await orderWith(["hoodie"], "sent_to_printer");
    expect((await retryFulfillment(orderId)).status).toBe("already-fulfilled");
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });

  it("refuses a pending order", async () => {
    const { orderId } = await orderWith(["hoodie"], "pending", null);
    expect(await retryFulfillment(orderId)).toMatchObject({
      status: "refused",
      reason: "not-retryable:pending",
    });
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
  });
});

describe("resendJobSheet", () => {
  it("sends the sheet again for an order that already has print files", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    await releaseApprovedOrder(orderId);
    sendJobSheetMock.mockClear();

    const result = await resendJobSheet(orderId);

    expect(result.status).toBe("sent");
    expect(sendJobSheetMock).toHaveBeenCalledTimes(1);
  });

  it("changes nothing: a re-send never rebuilds a print file", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    await releaseApprovedOrder(orderId);
    derivePrintBytesMock.mockClear();

    await resendJobSheet(orderId);

    // The shop is being sent the same links to the same files. A re-send that
    // remade them would hand them a second sheet pointing at different bytes.
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect(generatePortraitMock).not.toHaveBeenCalled();
  });

  it("leaves a breadcrumb, which is the whole reason it lives here", async () => {
    // Every other thing that mails the print shop writes a fulfillment_events
    // row. A re-send that reached past this module would be the one job sheet in
    // the shop's history with no trace, which is the one someone will need.
    const { orderId } = await orderWith(["hoodie"]);
    await releaseApprovedOrder(orderId);

    await resendJobSheet(orderId);

    const events = await eventsFor(orderId);
    const resends = events.filter(
      (event) => event.step === "job-sheet" && event.detail?.startsWith("re-sent"),
    );
    expect(resends).toHaveLength(1);
    expect(resends[0].outcome).toBe("ok");
  });

  it("does not move the order: a re-send is a message about it, not a step in it", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    await releaseApprovedOrder(orderId);
    const db = await getDb();
    await db.update(orders).set({ status: "printed" }).where(eq(orders.id, orderId));

    await resendJobSheet(orderId);

    // An order at printed whose sheet went astray is still printed. Dragging it
    // back to sent_to_printer to explain the re-send would lose that.
    expect((await readOrder(orderId)).status).toBe("printed");
  });

  it("refuses an order with no print files, and sends nothing", async () => {
    // There is nothing to print, so a sheet would send the shop a job it cannot
    // do. The fix for that order is a retry, not a re-send.
    const { orderId } = await orderWith(["hoodie"]);

    const result = await resendJobSheet(orderId);

    expect(result).toMatchObject({ status: "refused", reason: "no-print-files" });
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });

  it("refuses when only some lines have print files", async () => {
    // A sheet that links three garments and two files is a sheet the shop has to
    // ring us about.
    const { orderId } = await orderWith(["hoodie", "tote"]);
    derivePrintBytesMock
      .mockResolvedValueOnce(PNG_BYTES)
      .mockRejectedValueOnce(new Error("the second one failed"));
    vi.spyOn(console, "error").mockImplementation(() => {});
    await releaseApprovedOrder(orderId);
    sendJobSheetMock.mockClear();

    const result = await resendJobSheet(orderId);

    expect(result).toMatchObject({ status: "refused", reason: "no-print-files" });
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });

  it("refuses an order that does not exist", async () => {
    await expect(resendJobSheet(randomUUID())).resolves.toMatchObject({
      status: "refused",
      reason: "order-not-found",
    });
  });

  it("reports a failed send loudly, and records it as failed", async () => {
    const { orderId } = await orderWith(["hoodie"]);
    await releaseApprovedOrder(orderId);
    sendJobSheetMock.mockResolvedValue({ ok: false, error: new Error("smtp down") });
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await resendJobSheet(orderId);

    expect(result).toMatchObject({ status: "sent" });
    expect(result.status === "sent" && result.jobSheet.ok).toBe(false);
    expect(consoleError).toHaveBeenCalled();

    const events = await eventsFor(orderId);
    expect(
      events.some(
        (event) => event.step === "job-sheet" && event.outcome === "failed",
      ),
    ).toBe(true);
  });
});

describe("fulfillPaidOrder: the drawing half", () => {
  beforeEach(() => {
    // The drawing half composites through sharp, so it needs a real picture.
    generatePortraitMock.mockResolvedValue({
      portraitBytes: REAL_PNG,
      promptVersion: "test",
    });
  });

  it("draws, asks the customer to look, and prints nothing", async () => {
    const { orderId, artworkIds } = await unapprovedOrder(["hoodie"]);
    const result = await fulfillPaidOrder(orderId);

    expect(result.status).toBe("awaiting-approval");
    // Still paid: "paid with unapproved artwork" IS awaiting approval, and the
    // one thing that must not have happened is a job sheet.
    expect((await readOrder(orderId)).status).toBe("paid");
    expect(sendJobSheetMock).not.toHaveBeenCalled();
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    const [item] = await readItems(orderId);
    expect(item.printKey).toBeNull();

    // Both plates, from one drawing per side.
    const db = await getDb();
    const [artwork] = await db
      .select()
      .from(artworks)
      .where(eq(artworks.id, artworkIds[0]));
    expect(artwork.frontKey).toBeTruthy();
    expect(artwork.backKey).toBeTruthy();
  });

  it("does not redraw an artwork that already has its plates", async () => {
    // A duplicate ITN, a retry or an impatient admin must not pay for a second
    // portrait, still less replace one the customer may have approved already.
    const { orderId } = await orderWith(["hoodie"]);

    await fulfillPaidOrder(orderId);

    expect(generatePortraitMock).not.toHaveBeenCalled();
    const events = await eventsFor(orderId);
    expect(
      events.find((event) => event.step === "draw-artwork")?.outcome,
    ).toBe("skipped");
  });

  it("tells the customer before it flags, when drawing fails", async () => {
    const { orderId } = await unapprovedOrder(["hoodie"]);
    generatePortraitMock.mockRejectedValue(new Error("the model refused"));
    vi.spyOn(console, "warn").mockImplementation(() => {});
    vi.spyOn(console, "error").mockImplementation(() => {});

    const result = await fulfillPaidOrder(orderId);

    expect(result.status).toBe("flagged");
    // A paid order never goes silent. The delay notice goes out BEFORE the flag
    // so a mail failure cannot swallow the only thing they were going to hear.
    const events = await eventsFor(orderId);
    expect(
      events.find((event) => event.step === "draw-artwork")?.outcome,
    ).toBe("failed");
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });
});

describe("releaseApprovedOrder: the gate in front of the press", () => {
  it("refuses to print artwork nobody has approved", async () => {
    // The whole promise of the shop, in one assertion.
    const { orderId } = await unapprovedOrder(["hoodie"]);

    const result = await releaseApprovedOrder(orderId);

    expect(result).toMatchObject({ status: "refused", reason: "not-approved" });
    expect(sendJobSheetMock).not.toHaveBeenCalled();
    expect(derivePrintBytesMock).not.toHaveBeenCalled();
    expect((await readOrder(orderId)).status).toBe("paid");
  });

  it("refuses when only one artwork of several is approved", async () => {
    // An order with two garments has two portraits. Printing the approved one
    // alongside an unapproved one is exactly the mistake this prevents.
    const { orderId, artworkIds } = await unapprovedOrder(["hoodie", "tote"]);
    const db = await getDb();
    await db
      .update(artworks)
      .set({ approvedAt: new Date() })
      .where(eq(artworks.id, artworkIds[0]));

    const result = await releaseApprovedOrder(orderId);

    expect(result).toMatchObject({ status: "refused", reason: "not-approved" });
    expect(sendJobSheetMock).not.toHaveBeenCalled();
  });

  it("never calls the image provider, however ordinary the order", async () => {
    // The invariant that used to belong to fulfilment as a whole. Printing
    // still never draws: the print file is a resize of the approved bytes, and
    // a second trip to a non-deterministic model would print a portrait nobody
    // agreed to.
    const { orderId } = await orderWith(["hoodie", "tote"]);

    await releaseApprovedOrder(orderId);

    expect(generatePortraitMock).not.toHaveBeenCalled();
  });
});
